repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^argocd-apps/.*/chart/
      - id: end-of-file-fixer
        exclude: ^argocd-apps/.*/chart/
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^argocd-apps/.*/chart/
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: [-d, relaxed]
        exclude: ^argocd-apps/.*/chart/
