# syntax=docker/dockerfile:1

FROM rust:1.76 as builder

# Install mingw-w64 for Windows cross-compilation
RUN apt-get update && apt-get install -y mingw-w64 && rm -rf /var/lib/apt/lists/*

# Add the Windows target
RUN rustup target add x86_64-pc-windows-gnu

WORKDIR /app
COPY src-build/ .
RUN cargo build --release --target x86_64-pc-windows-gnu

FROM busybox
WORKDIR /output
COPY --from=builder /app/target/x86_64-pc-windows-gnu/release/*.exe /output/ 