apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector-metrics
  namespace: observability
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/part-of: observability-stack
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector 