apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-stack-poc-kube-prometheus
  namespace: observability
  labels:
    app: prometheus
    prometheus: prometheus-stack-poc-kube-prometheus
    release: prometheus-stack-poc
spec:
  serviceAccountName: prometheus-stack-poc-kube-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: prometheus-stack-poc
  serviceMonitorNamespaceSelector:
    matchLabels:
      name: observability
  podMonitorSelector:
    matchLabels:
      release: prometheus-stack-poc
  podMonitorNamespaceSelector:
    matchLabels:
      name: observability
  ruleSelector:
    matchLabels:
      release: prometheus-stack-poc
  ruleNamespaceSelector:
    matchLabels:
      name: observability
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m
  retention: 15d
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "standard"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi 