fullnameOverride: pushgateway

resources:
  limits:
    memory: 128Mi
    cpu: 250m
  requests:
    memory: 64Mi
    cpu: 50m

service:
  type: ClusterIP
  port: 9091

persistentVolume:
  enabled: false
