apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: prometheus-crds
            syncWave: "0"
            repoURL: https://prometheus-community.github.io/helm-charts
            chart: kube-prometheus-stack
            valuesFile: prometheus-crds-values.yaml
          
          - name: prometheus-stack
            syncWave: "1"
            repoURL: https://prometheus-community.github.io/helm-charts
            chart: kube-prometheus-stack
            valuesFile: prometheus-stack-values.yaml
          
          - name: opentelemetry-collector
            syncWave: "2"
            chart: opentelemetry-collector
            repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
            valuesFile: opentelemetry-values.yaml
  
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
        # For CRDs application, don't prune when deleted
        argocd.argoproj.io/sync-options: PruneLast=true
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        chart: '{{chart}}'
        helm:
          valueFiles:
            - '{{valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 