apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds-poc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/description: "POC Prometheus Operator CRDs"
  labels:
    app.kubernetes.io/part-of: observability-stack
    app.kubernetes.io/component: crds
    environment: poc
    team: platform
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator.git
    targetRevision: v0.68.0
    path: example/prometheus-operator-crd

  syncPolicy:
    automated:
      prune: false  # Never delete CRDs automatically
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m 