apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: observability-stack
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.71.0
    chart: jaeger
    helm:
      values: |
        # Jaeger Configuration - In-Memory Storage
        storage:
          type: memory
          options:
            memory:
              maxTraces: 50000
        
        # Query service configuration
        query:
          service:
            type: ClusterIP
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
        
        # Collector configuration
        collector:
          service:
            type: ClusterIP
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
        
        # Disable agent since we're using OpenTelemetry
        agent:
          enabled: false
        
        # Disable Cassandra and other storage backends
        cassandra:
          enabled: false
        elasticsearch:
          enabled: false
        kafka:
          enabled: false
        
        # Ingress configuration (optional)
        ingress:
          enabled: false
        
        # Service account configuration
        serviceAccount:
          create: true
          name: jaeger
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 