apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: observability-stack
  namespace: argocd

resources:
  # Istio sidecar mesh
  - gateway-api-crds/app.yaml
  - istio-base/app.yaml
  - istio-istiod/app.yaml
  - istio-mesh-config/app.yaml
  - kiali/app.yaml
  # Existing apps
  - traefik/app.yaml
  - grafana/app.yaml
  - victoria-metrics/app.yaml
  - node-exporter/app.yaml
  - jaeger/app.yaml
  - loki/app.yaml
  - opentelemetry-collector/app.yaml
  - observability-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: observability-stack
      app.kubernetes.io/managed-by: argocd
