apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: observability-stack
  namespace: argocd

resources:
- crds-poc-app.yaml
- opentelemetry-collector-app.yaml
- prometheus-stack-poc.yaml
- grafana-dashboards/argo-cd.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: observability-stack
    app.kubernetes.io/managed-by: argocd

commonAnnotations:
  argocd.argoproj.io/description: "Kubernetes Observability Stack with Prometheus, Grafana, and OpenTelemetry Collector" 