apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: observability-stack
  namespace: argocd

resources:
  - grafana-app.yaml
  - prometheus-app.yaml
  - jaeger-app.yaml
  - clickhouse-app.yaml
  - opentelemetry-collector-app.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: observability-stack
      app.kubernetes.io/managed-by: argocd 