# CRDs-only configuration for kube-prometheus-stack
# This installs only the Custom Resource Definitions, nothing else

prometheusOperator:
  createCustomResource: true
  enabled: true

# Disable all other components
prometheus:
  enabled: false
alertmanager:
  enabled: false
grafana:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false

# Only install CRDs
crds:
  enabled: true 