apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    helm:
      values: |
        # CRDs are installed by separate application
        prometheusOperator:
          createCustomResource: true  # CRDs already installed
          enabled: true

        nodeExporter:
          enabled: false

        grafana:
          adminPassword: admin
          service:
            type: LoadBalancer
          persistence:
            enabled: true
            size: 10Gi

        prometheus:
          prometheusSpec:
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
            additionalScrapeConfigs:
              - job_name: 'opentelemetry-collector'
                static_configs:
                  - targets: ['opentelemetry-collector.observability.svc.cluster.local:9464']
                metrics_path: /metrics
                scrape_interval: 15s

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 