apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    helm:
      values: |
        # CRDs-only configuration for kube-prometheus-stack
        # This installs only the Custom Resource Definitions, nothing else

        prometheusOperator:
          createCustomResource: true
          enabled: true

        # Disable all other components
        prometheus:
          enabled: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        nodeExporter:
          enabled: false
        kubeStateMetrics:
          enabled: false

        # Only install CRDs
        crds:
          enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 