apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: observability-stack
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.1.10
    chart: prometheus
    helm:
      values: |
        # Prometheus Configuration
        server:
          retention: 15d
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
            requests:
              memory: 1Gi
              cpu: 500m
          persistence:
            enabled: true
            size: 20Gi
          service:
            type: ClusterIP
            port: 9090
        alertmanager:
          enabled: true
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              memory: 128Mi
              cpu: 100m
          persistence:
            enabled: true
            size: 5Gi
        kube-state-metrics:
          enabled: true
        node-exporter:
          enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 