# CRDs are installed by separate application
prometheusOperator:
  createCustomResource: false  # CRDs already installed
  enabled: true

nodeExporter:
  enabled: false

grafana:
  adminPassword: admin
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    size: 10Gi

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    additionalScrapeConfigs:
      - job_name: 'opentelemetry-collector'
        static_configs:
          - targets: ['opentelemetry-collector.observability.svc.cluster.local:9464']
        metrics_path: /metrics
        scrape_interval: 15s

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi 