apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: observability-stack
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.7.0
    chart: kube-prometheus-stack
    helm:
      values: |
        # Basic Prometheus Stack Configuration
        grafana:
          adminPassword: admin123
          service:
            type: ClusterIP
          persistence:
            enabled: true
            size: 10Gi
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 500m
        
        prometheus:
          prometheusSpec:
            retention: 15d
            resources:
              limits:
                memory: 2Gi
                cpu: 1000m
              requests:
                memory: 1Gi
                cpu: 500m
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
        
        alertmanager:
          alertmanagerSpec:
            resources:
              limits:
                memory: 256Mi
                cpu: 250m
              requests:
                memory: 128Mi
                cpu: 100m
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
        
        # Disable components we don't need
        kubelet:
          enabled: false
        kubeApiServer:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        nodeExporter:
          enabled: false
        etcd:
          enabled: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 