apiVersion: v2
description: 'MongoDB Controllers for Kubernetes translate the human knowledge of
  creating a MongoDB instance into a scalable, repeatable, and standardized method. '
home: https://github.com/mongodb/mongodb-kubernetes
icon: https://mongodb-images-new.s3.eu-west-1.amazonaws.com/leaf-green-dark.png
keywords:
- mongodb
- database
- nosql
kubeVersion: '>=1.16-0'
maintainers:
- email: support@mongodb.com
  name: MongoDB
name: mongodb-kubernetes
type: application
version: 1.7.0
