deployment:
  replicas: 1

resources:
  limits:
    memory: 256Mi
    cpu: 250m
  requests:
    memory: 128Mi
    cpu: 100m

service:
  spec:
    type: NodePort

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    nodePort: 30080
    protocol: TCP
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    nodePort: 30443
    protocol: TCP
  metrics:
    port: 8082
    expose:
      default: false
    protocol: TCP

api:
  dashboard: true
  insecure: true

ingressRoute:
  dashboard:
    enabled: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik"
