apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operators
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: observability-stack
spec:
  project: default
  source:
    repoURL: https://github.com/nikhil-pagote/k8s_observebility.git
    targetRevision: HEAD
    path: argocd-apps/clickhouse-operators/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
