apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app-test
  namespace: observability
  labels:
    release: prometheus-stack-poc
spec:
  selector:
    matchLabels:
      app: sample-app
  endpoints:
    - port: http
      interval: 30s
      path: / 