auth:
  strategy: anonymous

server:
  web_root: "/kiali"

external_services:
  prometheus:
    url: "http://victoria-metrics.observability.svc.cluster.local:8428"
  tracing:
    enabled: true
    provider: jaeger
    in_cluster_url: "http://jaeger.observability.svc.cluster.local:16686"
    use_grpc: false
  grafana:
    enabled: true
    in_cluster_url: "http://grafana.observability.svc.cluster.local:80"
    url: "http://localhost:30080/grafana"
  istio:
    root_namespace: istio-system

deployment:
  ingress:
    enabled: true
    override_yaml:
      metadata:
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web
      spec:
        rules:
          - host: localhost
            http:
              paths:
                - path: /kiali
                  pathType: Prefix
                  backend:
                    service:
                      name: kiali
                      port:
                        number: 20001

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
