apiVersion: v2
appVersion: 1.0.0
dependencies:
- alias: mongodb-operator
  name: mongodb-kubernetes
  repository: https://mongodb.github.io/helm-charts
  version: ~1.7.0
- alias: clickhouse-operator
  name: clickhouse-operator-helm
  repository: oci://ghcr.io/clickhouse
  version: ~0.0.2
description: Operator dependencies for ClickStack. Install this chart before installing
  clickstack/clickstack to ensure CRDs are registered.
home: https://clickhouse.com/docs/use-cases/observability/clickstack
name: clickstack-operators
type: application
version: 1.0.0
