adminPassword: admin123

image:
  tag: "12.4.3"

initChownData:
  enabled: false

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 10Gi

resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 512Mi
    cpu: 500m

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        url: http://victoria-metrics.observability.svc.cluster.local:8428
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 15s
          queryTimeout: 60s
          httpMethod: POST
      - name: Loki
        type: loki
        url: http://loki.observability.svc.cluster.local:3100
        access: proxy
        editable: true

dashboards:
  default:
    kubernetes-views-global:
      file: dashboards/kubernetes-views-global.json
    traefik:
      file: dashboards/traefik.json
    node-exporter:
      gnetId: 1860
      revision: 22
      datasource: VictoriaMetrics
    victoria-metrics:
      gnetId: 10229
      revision: 35
      datasource: VictoriaMetrics

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/default

grafana.ini:
  server:
    root_url: http://localhost:30080/grafana
    serve_from_sub_path: true
  auth.anonymous:
    enabled: false
  security:
    allow_embedding: true
