auth:
  username: default
  password: clickhouse123

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 20Gi

resources:
  limits:
    memory: 2Gi
    cpu: 2000m
  requests:
    memory: 1Gi
    cpu: 1000m

replicaCount: 1
